environments:
    dev:
        url: http://dev.bar.com
        name: Developer Setup
    prod:
        url: http://foo.bar.com
        name: My Cool App
        
my:
   servers:
       - dev.bar.com
       - foo.bar.com
       
server:
    address: 192.168.1.100
---
spring:
    profiles: development
server:
    address: 127.0.0.1
---
spring:
    profiles: production
server:
    address: 192.168.1.120
---
spring:
  profiles: default
security:
  user:
    password: weak